imports:
    - { resource: ckfinder_config.php }

ckfinder:
    connector:
        authenticationClass: App\SecurityAuths\CKFinderAuth
        licenseName: '%env(CKFINDER_LICENSENAME)%'
        licenseKey: '%env(CKFINDER_LICENSEKEY)%'