easy_admin:
    site_name: 'kuba-raisen admin'
    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        menu:
            - { label: 'Products' }
            - { entity: 'Activity', label: 'Activities' , icon: 'location-arrow'}
            - { entity: 'Destination', label: 'Destinations' , icon: 'map-marker-alt'}
            - { entity: 'Story', label: 'Stories' , icon: 'bookmark'}
            - { entity: 'Interest', label: 'Interest' , icon: 'heart'}
            - { entity: 'FilterTag', label: 'Tags' , icon: 'tags'}


            - { label: 'Management' }
            - { label: 'Pages', route: 'backend_dynamic_page_index', icon: 'file-alt' }
            - { label: 'Menus', route: 'backend_dynamic_page_index', icon: 'bars' }
            - { label: 'Browse Images', route: 'ckfinder_fullpage', icon: 'images'}
            - { entity: 'Image', label: 'Manage Images', icon: 'images'}
            - { label: 'Config', route: 'ckfinder_fullpage', icon: 'cogs' }

            - { label: 'Users' }
            - { entity: 'User', params: { action: 'new' }, label: 'New User' , icon: 'user-plus'}
            - { entity: 'User',label: 'All Users' , icon: 'users'}



    entities:
#        # List the entity class name you want to manage
        Interest:
            class: App\Entity\Interest
            list:
                fields:
                    - { property: 'active' }
                    - { property: 'title' }
                    - { property: 'image.imageName', label: 'Image', type: 'image', base_path: '%app.path.uploaded_images%' }

            form:
                fields:
                    - { type: 'group', label: 'Interest Data', icon: 'comments', columns: 4 }
                    - { property: 'title' }
                    - { property: 'description' }
                    - { property: 'filterTags', type: 'entity' }

                    - { type: 'group', label: 'Featured Image', icon: 'image', columns: 4 }
                    - { property: 'image', label: 'Featured Image', type: 'App\Form\ImageUploadType' }

                    - { type: 'group', label: 'Activity settings', icon: 'cogs', columns: 4 }
                    - { property: 'active', label: 'The Interest is Active' }
                    - { property: 'priority' , label: 'Priority on results' }

#
#        DynamicPage:
#            class: App\Entity\DynamicPage
#            list:
#                fields:
#                    - { property: 'id' }
#                    - { property: 'pageName' }
#                    - { property: 'pageTitle' }
#                    - { property: 'language' }
#                    - { property: 'pageTemplate' }
#                    - { property: 'modified_by' }
#            form:
#                fields:
#                    - { type: 'group', label: 'Page Info', icon: 'comments', columns: 8 }
#                    - { property: 'pageName' }
#                    - { property: 'pageTitle' }
#
#                    - { type: 'group', label: 'Language and Translation', icon: 'globe', columns: 4 }
#                    - { property: 'language', type: 'choice', type_options: {choices: {en: 'en', de: 'de',es: 'es'}} }
#                    - { property: 'translation_from', type: 'entity', class: 'App\Entity\DynamicPage' }
#
#                    - { property: 'pageTemplate' }

        User:
            class: App\Entity\User

        Activity:
            class: App\Entity\Activity
            controller: App\Controller\Admin\ActivitiesController
            list:
                fields:
                    - { property: 'ID', label: 'ID' }
                    - { property: 'active' }
                    - { property: 'name' }
                    - { property: 'initPrice' , label: 'Initial price'}

            form:
                fields:
                    - { type: 'group', label: 'Activity Info', icon: 'location-arrow', columns: 8 }
                    - { property: 'name' }
                    - { property: 'filterTags', type: 'entity' }
                    - { property: 'destinations', type: 'entity' }

#                    - { property: 'imageFile', type: 'vich_image' }


                    - { type: 'group', label: 'Activity settings', icon: 'cogs', columns: 4 }
                    - { property: 'active', label: 'The Activity is Active' }
                    - { property: 'initPrice', type: 'money' , label: 'Starting price' }
                    - { property: 'priority' , label: 'Priority on results' }

                    - { type: 'group', label: 'Activity description', icon: 'bookmark', columns: 8 }
                    - { property: 'description', type: 'fos_ckeditor' }
                    - { property: 'descriptionFragment', label: '-', help: 'Add many fragments as you need to describe this destination', type: 'collection',  type_options: { entry_type: 'App\Form\DescriptionFragmentType', by_reference: true } }


                    - { type: 'group', label: 'Featured Image', icon: 'image', columns: 4 }
#                    - { property: 'image', template: 'backend/easyadmin/vich_uploader_image.html.twig' }
                    - { property: 'imageFile',label: 'Featured Image', type: 'vich_image' }
                    - { property: 'alternativeText' }


                    - { type: 'group', label: 'Activity details', icon: 'book-open', columns: 8 }
                    - { property: 'contentItineraryTitle', type: 'text' }
                    - { property: 'contentItineraryContent', type: 'fos_ckeditor' }
                    - { property: 'contentIncludedTitle', type: 'text' }
                    - { property: 'contentIncludedContent', type: 'fos_ckeditor' }
                    - { property: 'contentNotIncludedTitle', type: 'text' }
                    - { property: 'contentNotIncludedContent', type: 'fos_ckeditor' }
                    - { property: 'contentCostAndDatesTitle', type: 'text' }
                    - { property: 'contentCostAndDatesContent', type: 'fos_ckeditor' }




                    - { type: 'group', label: 'Gallery', icon: 'images', columns: 4 }
                    - { type: 'section', label: 'Images from Gallery', icon: 'folder-open', help: 'Previously uploaded images' }
                    - { property: 'uploadedImages', label: 'Add images from Gallery',  help: 'Select one or more images', type: 'entity',  type_options: { class: 'App\Entity\Image', multiple: true, attr: {'data-widget': 'select2'} } }
                    - { type: 'section', label: 'Images linked to this activity', icon: 'images', help: 'You can upload new images from here' }
                    - { property: 'gallery', label: '-', type: 'collection',  type_options: { entry_type: 'App\Form\ImageUploadType', by_reference: true } }

        FilterTag:
            class: App\Entity\FilterTag

        Destination:
            class: App\Entity\Destination
            list:
                fields:
                    - { property: 'ID', label: 'ID' }
                    - { property: 'active' }
                    - { property: 'name' }
                    - { property: 'image', label: 'Featured Image', type: 'image' , base_path: '%app.path.uploaded_images%' }

            form:
                fields:
                    - { type: 'group', label: 'Destination Info', icon: 'map-marker-alt', columns: 8 }
                    - { property: 'name' }
                    - { property: 'filterTags', type: 'entity', help: 'Select the Tags related to this Destination. Users can use it at search' }
                    - { property: 'activities', type: 'entity', help: 'Select the activities related to this Destination' }


                    - { type: 'group', label: 'Destination settings', icon: 'cogs', columns: 4 }
                    - { property: 'active', label: 'The Destination is Active' }
                    - { property: 'priority' , label: 'Priority on results' }

                    - { type: 'group', label: 'Destination description', icon: 'bookmark', columns: 8 }
                    - { property: 'description', type: 'fos_ckeditor' }


                    - { type: 'group', label: 'Featured Image', icon: 'image', columns: 4 }
                    #                    - { property: 'image', template: 'backend/easyadmin/vich_uploader_image.html.twig' }
                    - { property: 'imageFile',label: 'Featured Image', type: 'vich_image' }
                    - { property: 'alternativeText' }


                    - { type: 'group', label: 'Destination details', icon: 'book-open', columns: 8 }
                    - { property: 'descriptionFragment', label: '-', help: 'Add many fragments as you need to describe this destination', type: 'collection',  type_options: { entry_type: 'App\Form\DescriptionFragmentType', by_reference: true } }


                    - { type: 'group', label: 'Gallery', icon: 'images', columns: 4 }
                    - { type: 'section', label: 'Images from Gallery', icon: 'folder-open', help: 'Previously uploaded images' }
                    - { property: 'uploadedImages', label: 'Add images from Gallery',  help: 'Select one or more images', type: 'entity',  type_options: { class: 'App\Entity\Image', multiple: true, attr: {'data-widget': 'select2'} } }
                    - { type: 'section', label: 'Images linked to this activity', icon: 'images', help: 'You can upload new images from here' }
                    - { property: 'gallery', label: '-', type: 'collection',  type_options: { entry_type: 'App\Form\ImageUploadType', by_reference: true } }


        Story:
            class: App\Entity\ActivityStory
            list:
                fields:
                    - { property: 'active' }
                    - { property: 'title' }
                    - { property: 'priority' }
                    - { property: 'image.imageName', label: 'Image', type: 'image', base_path: '%app.path.uploaded_images%' }
            form:
                fields:
                    - { type: 'group', label: 'Story Info', icon: 'bookmark', columns: 8 }
                    - { property: 'title' }
                    - { property: 'content', type: 'fos_ckeditor' }

                    #                    - { property: 'imageFile', type: 'vich_image' }


                    - { type: 'group', label: 'Story settings', icon: 'cogs', columns: 4 }
                    - { property: 'active', label: 'The Story is Active' }
                    - { property: 'priority' , label: 'Priority on results' }
                    - { type: 'section', label: 'Featured Image', icon: 'image' }
                    - { property: 'image', label: 'Featured Image', type: 'App\Form\ImageUploadType' }



        Image:
            class: App\Entity\Image
            list:
                fields:
                    - { property: 'imageName', type: 'image', base_path: '%app.path.uploaded_images%' }
                    - { property: 'description' }
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'description' }

        #- App\Entity\User
