easy_admin:
    site_name: 'kuba-raisen admin'
    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        menu:
            - { label: 'Products' }
            - { entity: 'Activities', label: 'Activities' , icon: 'location-arrow'}
            - { entity: 'Destination', label: 'Destinations' , icon: 'map-marker-alt'}
            - { entity: 'Interest', label: 'Interest' , icon: 'heart'}
            - { entity: 'FilterTags', label: 'Tags' , icon: 'tags'}
            - { entity: 'Stories', label: 'Stories' , icon: 'bookmark'}

            - { label: 'Management' }
            - { label: 'Pages', route: 'backend_dynamic_page_index', icon: 'file-alt' }
            - { label: 'Menus', route: 'backend_dynamic_page_index', icon: 'bars' }
            - { label: 'Browse Images', route: 'ckfinder_fullpage', icon: 'images'}
            - { entity: 'Images', label: 'Manage Images', icon: 'images'}
            - { label: 'Config', route: 'ckfinder_fullpage', icon: 'cogs' }

            - { label: 'Users' }
            - { entity: 'Users', params: { action: 'new' }, label: 'New User' , icon: 'user-plus'}
            - { entity: 'Users',label: 'All Users' , icon: 'users'}



    entities:
#        # List the entity class name you want to manage
        Interest:
            class: App\Entity\Interest
            list:
                fields:
                    - { property: 'image', template: 'backend/easyadmin/vich_uploader_image.html.twig' }
                    - { property: 'title' }
                    - { property: 'modified_by' }
            form:
                fields:
                    - { type: 'group', label: 'Interest Data', icon: 'comments', columns: 8 }

                    - { property: 'title' }
                    - { property: 'description' }
                    - { property: 'filterTags', type: 'entity' }



                    - { type: 'group', label: 'Language and Translation', icon: 'globe', columns: 4 }
                    - { property: 'language', type: 'choice', type_options: {choices: {en: 'en', de: 'de',es: 'es'}} }
                    - { property: 'translation_from', type: 'entity' }

                    - { type: 'group', label: 'Image Info', icon: 'image', columns: 4 }
                    #- { property: 'image', template: 'backend/easyadmin/vich_uploader_image.html.twig' }
                    #- { property: 'imageFile', type: 'vich_image' }
                    - { property: 'alternativeText' }
            show:
                - { property: 'title' }
                - { property: 'description' }
                - { property: 'modified_by'}

        DynamicPage:
            class: App\Entity\DynamicPage
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'pageName' }
                    - { property: 'pageTitle' }
                    - { property: 'language' }
                    - { property: 'pageTemplate' }
                    - { property: 'modified_by' }
            form:
                fields:
                    - { type: 'group', label: 'Page Info', icon: 'comments', columns: 8 }
                    - { property: 'pageName' }
                    - { property: 'pageTitle' }

                    - { type: 'group', label: 'Language and Translation', icon: 'globe', columns: 4 }
                    - { property: 'language', type: 'choice', type_options: {choices: {en: 'en', de: 'de',es: 'es'}} }
                    - { property: 'translation_from', type: 'entity', class: 'App\Entity\DynamicPage' }

                    - { property: 'pageTemplate' }

        Users:
            class: App\Entity\User

        Activities:
            class: App\Entity\Activity
            controller: App\Controller\Admin\ActivitiesController
            list:
                fields:
                    #- { property: 'image', template: 'backend/easyadmin/vich_uploader_image.html.twig' }
                    - { property: 'active' }
                    - { property: 'name' }
                    - { property: 'initPrice' , label: 'Initial price'}
                    - { property: 'image', label: 'Featured Image', type: 'image' , base_path: '%app.path.uploaded_images%' }

#                    - { property: 'filterTags' }
#                    - { property: 'modified_by' }
            form:
                fields:
                    - { type: 'group', label: 'Activity Info', icon: 'location-arrow', columns: 8 }
                    - { property: 'name' }
                    - { property: 'filterTags', type: 'entity' }
                    - { property: 'destinations', type: 'entity' }

#                    - { property: 'imageFile', type: 'vich_image' }


                    - { type: 'group', label: 'Activity settings', icon: 'cogs', columns: 4 }
                    - { property: 'active', label: 'The Activity is Active' }
                    - { property: 'initPrice', type: 'money' , label: 'Starting price' }
                    - { property: 'priority' , label: 'Priority on results' }

                    - { type: 'group', label: 'Activity description', icon: 'bookmark', columns: 8 }
                    - { property: 'description', type: 'fos_ckeditor' }


                    - { type: 'group', label: 'Featured Image', icon: 'image', columns: 4 }
#                    - { property: 'image', template: 'backend/easyadmin/vich_uploader_image.html.twig' }
                    - { property: 'imageFile',label: 'Featured Image', type: 'vich_image' }
                    - { property: 'alternativeText' }


                    - { type: 'group', label: 'Activity details', icon: 'book-open', columns: 8 }
                    - { property: 'contentItineraryTitle', type: 'text' }
                    - { property: 'contentItineraryContent', type: 'fos_ckeditor' }
                    - { property: 'contentIncludedTitle', type: 'text' }
                    - { property: 'contentIncludedContent', type: 'fos_ckeditor' }
                    - { property: 'contentNotIncludedTitle', type: 'text' }
                    - { property: 'contentNotIncludedContent', type: 'fos_ckeditor' }
                    - { property: 'contentCostAndDatesTitle', type: 'text' }
                    - { property: 'contentCostAndDatesContent', type: 'fos_ckeditor' }




                    - { type: 'group', label: 'Gallery', icon: 'images', columns: 4 }
                    - { property: 'gallery', type: 'collection',  type_options: { entry_type: 'App\Form\ImageUploadType', by_reference: true } }
                show:
                    - { property: 'title' }
                    - { property: 'description' }
                    - { property: 'modified_by' }

        FilterTags:
            class: App\Entity\FilterTag

        Destination:
            class: App\Entity\Destination

        Stories:
            class: App\Entity\ActivityStory

        Images:
            class: App\Entity\Image
            list:
                fields:
                    - { property: 'imageName', type: 'image', base_path: '%app.path.uploaded_images%' }
                    - { property: 'description' }
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'description' }

        #- App\Entity\User
