fm_elfinder:
    instances:
        default:
            locale: es #'%locale%'
            editor: 'ckeditor'
            include_assets: true
            relative_path: true
            connector:
                debug: false
                roots:
                    uploads:
                        driver: Flysystem
                        #driver: LocalFileSystem
                        path: 
                        url: "%env(MEDIA_STATIC_HOST_URL)%uploads/images"
                        flysystem:
                              type: local
                              options:
                                local:
                                    path: '%kernel.project_dir%/%env(MEDIA_STATIC_PATH_DIRECTORY)%/uploads/images/'
                        
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 6M # also file upload sizes restricted in php.ini
                        
