# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    configs:
        my_config:
            toolbar: my_toolbar_1
    toolbars:
        configs:
            my_toolbar_1: [['Bold', 'Italic', 'Strike',  'Styles', 'Format','-', 'RemoveFormat'],['PasteText', 'PasteFromWord', '-'],['Link', 'Unlink', 'Anchor'],['NumberedList', 'BulletedList', 'Blockquote'],['Image', 'Table'], [ "Source"]]
