# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    configs:
        my_config:
            toolbar: my_toolbar_1
            extraPlugins: ["MapMarker", "MapPath"]
            allowedContent: true # 'span[data-map,class]'
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
            #filebrowserBrowseUrl: '/admin/ckfinder/modal'
            #filebrowserUploadUrl: '/admin/ckfinder/connector?command=QuickUpload&type=Files'
            #filebrowserUploadUrl: "/ckeditor_imageupload/?"
    toolbars:
        configs:
            my_toolbar_1: [['PasteText', 'PasteFromWord', '-'],['Bold', 'Italic', 'Strike', 'Styles', 'Format','-', 'RemoveFormat'],['Link', 'Unlink', 'Anchor'],['NumberedList', 'BulletedList', 'Blockquote'],['Image', 'Table'], [ "Source", "MapMarker", "MapPath","Maximize"]]
    plugins:
        MapMarker:
            path:     "/scripts/" # with trailing slash
            filename: "MapMarker.js"
        MapPath:
            path:     "/scripts/" # with trailing slash
            filename: "MapPath.js"

