twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/public/': public
    exception_controller: null
    globals:
        requestStack: '@App\Twig\AppRequestStack'
        pager: '@App\PageManager\PageManager'
# form_themes: ['bootstrap_4_layout.html.twig','@EasyAdmin/form/bootstrap_4.html.twig' ,'@FOSCKEditor/Form/ckeditor_widget.html.twig']


