fos_user:
  resource: '@FOSUserBundle/Resources/config/routing/all.xml'

easy_admin_bundle:
  resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
  prefix: /admin/
  type: annotation

controllers:
    resource: '../../src/Controller/'
    type: annotation
