fos_user:
  resource: '@FOSUserBundle/Resources/config/routing/all.xml'

easy_admin_bundle:
  resource: App\Controller\AdminController
#  prefix: /admin
  type: annotation

controllers:
    resource: '../../src/Controller/'
    exclude: '../src/Controller/{AdminController.php}'
    type: annotation
