ckfinder_connector:
    path:     /admin/ckfinder/connector
    defaults: { _controller: CKSource\Bundle\CKFinderBundle\Controller\CKFinderController::requestAction }

ckfinder_fullpage:
    path:     /admin/ckfinder/explore
    defaults: { _controller: CKSource\Bundle\CKFinderBundle\Controller\CKFinderController::examplesAction, example: fullpage }
