framework:
    secret: '%env(APP_SECRET)%'
    default_locale: 'de'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

    assets:
        #version: 'v1'
        #version_format: '%%s?ver=%%s'
        base_path: ~
        base_url: ['%env(MEDIA_STATIC_HOST_URL)%']
        packages:
            img:
                base_path: /static/images/
#
#    templating:
#        engines: ['twig', 'php']
    ide: 'phpstorm://open?url=file://%%f&line=%%l'

parameters:
    env(MEDIA_STATIC_HOST_URL): http://static.kuba-reisen.test
    env(MEDIA_STATIC_PATH_DIRECTORY): public/static
    env(EMAIL_ADDRESS): no-reply@kuba-reisen.de
    env(EMAIL_SENDER_NAME): Kuba-reisen

