<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190908000353 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP TABLE contact_planing_interest');
        $this->addSql('DROP TABLE destination_activity');
        $this->addSql('DROP TABLE destination_filter_tag');
        $this->addSql('DROP TABLE page_block');
        $this->addSql('ALTER TABLE activity CHANGE translation_from_id translation_from_id INT DEFAULT NULL, CHANGE modified_by_id modified_by_id INT DEFAULT NULL, CHANGE dynamic_page_id dynamic_page_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE alternative_text alternative_text VARCHAR(255) DEFAULT NULL, CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE image_original_name image_original_name VARCHAR(255) DEFAULT NULL, CHANGE image_mime_type image_mime_type VARCHAR(255) DEFAULT NULL, CHANGE image_size image_size INT DEFAULT NULL, CHANGE image_dimensions image_dimensions LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:simple_array)\', CHANGE priority priority INT DEFAULT NULL, CHANGE init_price init_price DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE contact_planing DROP name, DROP email, CHANGE travel_duration travel_duration VARCHAR(255) DEFAULT NULL, CHANGE self_consider self_consider INT DEFAULT NULL, CHANGE self_character self_character INT DEFAULT NULL, CHANGE self_luxury self_luxury INT DEFAULT NULL');
        $this->addSql('ALTER TABLE destination CHANGE modified_by_id modified_by_id INT DEFAULT NULL, CHANGE dynamic_page_id dynamic_page_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE alternative_text alternative_text VARCHAR(255) DEFAULT NULL, CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE image_original_name image_original_name VARCHAR(255) DEFAULT NULL, CHANGE image_mime_type image_mime_type VARCHAR(255) DEFAULT NULL, CHANGE image_size image_size INT DEFAULT NULL, CHANGE image_dimensions image_dimensions LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:simple_array)\', CHANGE priority priority INT DEFAULT NULL');
        $this->addSql('ALTER TABLE dynamic_page CHANGE modified_by_id modified_by_id INT DEFAULT NULL, CHANGE page_template page_template VARCHAR(255) DEFAULT NULL, CHANGE page_content page_content LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\'');
        $this->addSql('ALTER TABLE dynamic_page_revision DROP FOREIGN KEY FK_B5F79E14D23A8DFF');
        $this->addSql('ALTER TABLE dynamic_page_revision CHANGE dynamic_page_id dynamic_page_id INT DEFAULT NULL, CHANGE modified_by_id modified_by_id INT DEFAULT NULL, CHANGE page_content page_content LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\'');
        $this->addSql('ALTER TABLE dynamic_page_revision ADD CONSTRAINT FK_B5F79E14D23A8DFF FOREIGN KEY (dynamic_page_id) REFERENCES dynamic_page (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE filter_tag CHANGE translation_from_id translation_from_id INT DEFAULT NULL, CHANGE modified_by_id modified_by_id INT DEFAULT NULL, CHANGE pinned pinned TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE interest CHANGE translation_from_id translation_from_id INT DEFAULT NULL, CHANGE modified_by_id modified_by_id INT DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE alternative_text alternative_text VARCHAR(255) DEFAULT NULL, CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE image_original_name image_original_name VARCHAR(255) DEFAULT NULL, CHANGE image_mime_type image_mime_type VARCHAR(255) DEFAULT NULL, CHANGE image_size image_size INT DEFAULT NULL, CHANGE image_dimensions image_dimensions LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:simple_array)\'');
        $this->addSql('ALTER TABLE post CHANGE translation_from_id translation_from_id INT DEFAULT NULL, CHANGE modified_by_id modified_by_id INT DEFAULT NULL, CHANGE dynamic_page_id dynamic_page_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE alternative_text alternative_text VARCHAR(255) DEFAULT NULL, CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE image_original_name image_original_name VARCHAR(255) DEFAULT NULL, CHANGE image_mime_type image_mime_type VARCHAR(255) DEFAULT NULL, CHANGE image_size image_size INT DEFAULT NULL, CHANGE image_dimensions image_dimensions LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:simple_array)\'');
        $this->addSql('ALTER TABLE uploaded_image CHANGE dynamic_page_id dynamic_page_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE alternative_text alternative_text VARCHAR(255) DEFAULT NULL, CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE image_original_name image_original_name VARCHAR(255) DEFAULT NULL, CHANGE image_mime_type image_mime_type VARCHAR(255) DEFAULT NULL, CHANGE image_size image_size INT DEFAULT NULL, CHANGE image_dimensions image_dimensions LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:simple_array)\'');
        $this->addSql('ALTER TABLE fos_user CHANGE salt salt VARCHAR(255) DEFAULT NULL, CHANGE last_login last_login DATETIME DEFAULT NULL, CHANGE confirmation_token confirmation_token VARCHAR(180) DEFAULT NULL, CHANGE password_requested_at password_requested_at DATETIME DEFAULT NULL, CHANGE bio bio VARCHAR(300) DEFAULT NULL, CHANGE telephone telephone VARCHAR(255) DEFAULT NULL, CHANGE enterprise enterprise VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE alternative_text alternative_text VARCHAR(255) DEFAULT NULL, CHANGE image_name image_name VARCHAR(255) DEFAULT NULL, CHANGE image_original_name image_original_name VARCHAR(255) DEFAULT NULL, CHANGE image_mime_type image_mime_type VARCHAR(255) DEFAULT NULL, CHANGE image_size image_size INT DEFAULT NULL, CHANGE image_dimensions image_dimensions LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:simple_array)\'');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE contact_planing_interest (contact_planing_id INT NOT NULL, interest_id INT NOT NULL, INDEX IDX_30BE196999ED1572 (contact_planing_id), INDEX IDX_30BE19695A95FF89 (interest_id), PRIMARY KEY(contact_planing_id, interest_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE destination_activity (destination_id INT NOT NULL, activity_id INT NOT NULL, INDEX IDX_F2C4C96B816C6140 (destination_id), INDEX IDX_F2C4C96B81C06096 (activity_id), PRIMARY KEY(destination_id, activity_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE destination_filter_tag (destination_id INT NOT NULL, filter_tag_id INT NOT NULL, INDEX IDX_B964ADE3816C6140 (destination_id), INDEX IDX_B964ADE397F93D6F (filter_tag_id), PRIMARY KEY(destination_id, filter_tag_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE page_block (id INT AUTO_INCREMENT NOT NULL, dynamic_page_id INT NOT NULL, name VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, content LONGTEXT DEFAULT NULL COLLATE utf8mb4_unicode_ci, INDEX IDX_E59A68F4D23A8DFF (dynamic_page_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE contact_planing_interest ADD CONSTRAINT FK_30BE19695A95FF89 FOREIGN KEY (interest_id) REFERENCES interest (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contact_planing_interest ADD CONSTRAINT FK_30BE196999ED1572 FOREIGN KEY (contact_planing_id) REFERENCES contact_planing (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE destination_activity ADD CONSTRAINT FK_F2C4C96B816C6140 FOREIGN KEY (destination_id) REFERENCES destination (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE destination_activity ADD CONSTRAINT FK_F2C4C96B81C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE destination_filter_tag ADD CONSTRAINT FK_B964ADE3816C6140 FOREIGN KEY (destination_id) REFERENCES destination (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE destination_filter_tag ADD CONSTRAINT FK_B964ADE397F93D6F FOREIGN KEY (filter_tag_id) REFERENCES filter_tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE activity CHANGE translation_from_id translation_from_id INT DEFAULT NULL, CHANGE dynamic_page_id dynamic_page_id INT DEFAULT NULL, CHANGE modified_by_id modified_by_id INT DEFAULT NULL, CHANGE priority priority INT DEFAULT NULL, CHANGE init_price init_price DOUBLE PRECISION DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE alternative_text alternative_text VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_name image_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_original_name image_original_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_mime_type image_mime_type VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_size image_size INT DEFAULT NULL, CHANGE image_dimensions image_dimensions LONGTEXT DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci COMMENT \'(DC2Type:simple_array)\'');
        $this->addSql('ALTER TABLE contact_planing ADD name VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, ADD email VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, CHANGE travel_duration travel_duration VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE self_consider self_consider INT DEFAULT NULL, CHANGE self_character self_character INT DEFAULT NULL, CHANGE self_luxury self_luxury INT DEFAULT NULL');
        $this->addSql('ALTER TABLE destination CHANGE dynamic_page_id dynamic_page_id INT DEFAULT NULL, CHANGE modified_by_id modified_by_id INT DEFAULT NULL, CHANGE priority priority INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE alternative_text alternative_text VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_name image_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_original_name image_original_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_mime_type image_mime_type VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_size image_size INT DEFAULT NULL, CHANGE image_dimensions image_dimensions LONGTEXT DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci COMMENT \'(DC2Type:simple_array)\'');
        $this->addSql('ALTER TABLE dynamic_page CHANGE modified_by_id modified_by_id INT DEFAULT NULL, CHANGE page_template page_template VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE page_content page_content LONGTEXT DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci COMMENT \'(DC2Type:array)\'');
        $this->addSql('ALTER TABLE dynamic_page_revision DROP FOREIGN KEY FK_B5F79E14D23A8DFF');
        $this->addSql('ALTER TABLE dynamic_page_revision CHANGE dynamic_page_id dynamic_page_id INT NOT NULL, CHANGE modified_by_id modified_by_id INT DEFAULT NULL, CHANGE page_content page_content LONGTEXT DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci COMMENT \'(DC2Type:array)\'');
        $this->addSql('ALTER TABLE dynamic_page_revision ADD CONSTRAINT FK_B5F79E14D23A8DFF FOREIGN KEY (dynamic_page_id) REFERENCES dynamic_page (id)');
        $this->addSql('ALTER TABLE filter_tag CHANGE translation_from_id translation_from_id INT DEFAULT NULL, CHANGE modified_by_id modified_by_id INT DEFAULT NULL, CHANGE pinned pinned TINYINT(1) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE fos_user CHANGE salt salt VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE last_login last_login DATETIME DEFAULT \'NULL\', CHANGE confirmation_token confirmation_token VARCHAR(180) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE password_requested_at password_requested_at DATETIME DEFAULT \'NULL\', CHANGE bio bio VARCHAR(300) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE telephone telephone VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE enterprise enterprise VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE alternative_text alternative_text VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_name image_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_original_name image_original_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_mime_type image_mime_type VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_size image_size INT DEFAULT NULL, CHANGE image_dimensions image_dimensions LONGTEXT DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci COMMENT \'(DC2Type:simple_array)\'');
        $this->addSql('ALTER TABLE interest CHANGE translation_from_id translation_from_id INT DEFAULT NULL, CHANGE modified_by_id modified_by_id INT DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE alternative_text alternative_text VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_name image_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_original_name image_original_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_mime_type image_mime_type VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_size image_size INT DEFAULT NULL, CHANGE image_dimensions image_dimensions LONGTEXT DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci COMMENT \'(DC2Type:simple_array)\'');
        $this->addSql('ALTER TABLE post CHANGE translation_from_id translation_from_id INT DEFAULT NULL, CHANGE dynamic_page_id dynamic_page_id INT DEFAULT NULL, CHANGE modified_by_id modified_by_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE alternative_text alternative_text VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_name image_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_original_name image_original_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_mime_type image_mime_type VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_size image_size INT DEFAULT NULL, CHANGE image_dimensions image_dimensions LONGTEXT DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci COMMENT \'(DC2Type:simple_array)\'');
        $this->addSql('ALTER TABLE uploaded_image CHANGE dynamic_page_id dynamic_page_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE alternative_text alternative_text VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_name image_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_original_name image_original_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_mime_type image_mime_type VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE image_size image_size INT DEFAULT NULL, CHANGE image_dimensions image_dimensions LONGTEXT DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci COMMENT \'(DC2Type:simple_array)\'');
    }
}
